In [3]:
import pandas as pd
import numpy as np

In [4]:
df_clientes = pd.read_excel(r'C:\Users\pablo\iCloudDrive\Master - ThePower\Data Analyst V3\Repositoros_GitHub\Entrega_Phyton_For_Data\Entrega-Proyecto-Python-EDA\DataProyecto\Bruto\customer-details.xlsx')
df_clientes

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb
...,...,...,...,...,...,...,...
20110,20110,114469,0,2,2012-10-28,13,25f35a3f-0fd2-4e6a-b4d5-74fa1a1f4cfc
20111,20111,82207,0,1,2012-02-10,27,a3d2d088-3781-44ea-9944-a4a40df51285
20112,20112,135009,0,0,2012-09-14,17,3769cb72-26be-40f2-9a93-f752fc96d628
20113,20113,8486,1,1,2012-07-04,18,d507f6b3-a030-46d7-9615-61fe3f6b8028
20114,20114,144419,1,0,2012-04-12,29,8299f0a6-e4c0-49fc-87ab-81308b70f80f

In [5]:
df_clientes2 = pd.read_excel(r'C:\Users\pablo\iCloudDrive\Master - ThePower\Data Analyst V3\Repositoros_GitHub\Entrega_Phyton_For_Data\Entrega-Proyecto-Python-EDA\DataProyecto\Bruto\customer-details.xlsx',
                             sheet_name = 1)
df_clientes2

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,82407,0,1,2013-10-07,29,ef81336c-e41a-46d0-8a30-5d4ac3b836be
1,1,24877,0,0,2013-04-21,32,50b224ac-84b4-42a7-aba9-3e1d1d620479
2,2,78839,1,0,2013-11-25,21,9cb15c53-b647-464a-add9-09cdae04897c
3,3,113859,1,1,2013-01-06,12,f8aaf334-949d-4943-a214-b64fe9c088b4
4,4,147317,0,0,2013-07-10,14,885fe85a-3718-4760-a32a-a57628cf7528
...,...,...,...,...,...,...,...
8960,8960,139839,0,0,2013-12-10,8,6f7a03ac-c1b9-4acf-a28b-37cc8254a92e
8961,8961,65516,0,2,2013-10-01,26,ed489dce-7ccf-46ad-a0d4-bb71c566fa40
8962,8962,56664,1,0,2013-12-07,13,01b3ac53-b1bd-450a-be11-6893b3aeadd5
8963,8963,25089,0,1,2013-08-24,14,8906c203-a13f-4b10-985c-bd72bd01a011
8964,8964,77504,0,0,2013-06-30,6,ba7fb638-c6cb-4dc8-aad4-75456c3818c5

In [6]:
df_clientes3 = pd.read_excel(r'C:\Users\pablo\iCloudDrive\Master - ThePower\Data Analyst V3\Repositoros_GitHub\Entrega_Phyton_For_Data\Entrega-Proyecto-Python-EDA\DataProyecto\Bruto\customer-details.xlsx',
                             sheet_name = 2)
df_clientes3

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,168812,1,1,2014-06-10,27,4d6c811c-0f24-4a73-b374-2ebd1f80d46e
1,1,108615,2,1,2014-04-05,24,eef0f24f-cbdb-4c67-b371-09d7bc59695e
2,2,179041,0,2,2014-09-22,4,bbfdcedd-199d-4927-94bb-5dad051ff471
3,3,116639,2,2,2014-08-16,3,e8ebb67d-4ee1-4615-b701-eefe3af607eb
4,4,49537,0,1,2014-09-05,28,f7f79ace-0024-4505-a401-f340946f0942
...,...,...,...,...,...,...,...
14085,14085,156980,1,2,2014-05-17,7,5f432048-d515-4bb5-9c94-62db451f88d4
14086,14086,139820,0,0,2014-09-29,1,993bbbd6-4dbc-4a40-a408-f91f8462bee6
14087,14087,78470,2,2,2014-10-28,12,d6271666-319d-42c8-a741-cb22bf2c2093
14088,14088,144218,0,1,2014-07-01,9,f67fbfa8-6573-414d-a805-b26a2f1b1ceb
14089,14089,115155,0,2,2014-12-25,7,9727bc06-c11a-461a-a5bb-3d210467cc2a

In [7]:
df_clientes = pd.concat([df_clientes,df_clientes2,df_clientes3], axis = 0, ignore_index = True)
df_clientes

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb
...,...,...,...,...,...,...,...
43165,14085,156980,1,2,2014-05-17,7,5f432048-d515-4bb5-9c94-62db451f88d4
43166,14086,139820,0,0,2014-09-29,1,993bbbd6-4dbc-4a40-a408-f91f8462bee6
43167,14087,78470,2,2,2014-10-28,12,d6271666-319d-42c8-a741-cb22bf2c2093
43168,14088,144218,0,1,2014-07-01,9,f67fbfa8-6573-414d-a805-b26a2f1b1ceb
43169,14089,115155,0,2,2014-12-25,7,9727bc06-c11a-461a-a5bb-3d210467cc2a

In [8]:
df_clientes.drop('Unnamed: 0', axis = 1, inplace = True)
df_clientes

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb
...,...,...,...,...,...,...
43165,156980,1,2,2014-05-17,7,5f432048-d515-4bb5-9c94-62db451f88d4
43166,139820,0,0,2014-09-29,1,993bbbd6-4dbc-4a40-a408-f91f8462bee6
43167,78470,2,2,2014-10-28,12,d6271666-319d-42c8-a741-cb22bf2c2093
43168,144218,0,1,2014-07-01,9,f67fbfa8-6573-414d-a805-b26a2f1b1ceb
43169,115155,0,2,2014-12-25,7,9727bc06-c11a-461a-a5bb-3d210467cc2a

In [9]:
df_clientes.columns

Index(['Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'NumWebVisitsMonth',
       'ID'],
      dtype='object')

In [10]:
df_clientes.dtypes

Income                        int64
Kidhome                       int64
Teenhome                      int64
Dt_Customer          datetime64[ns]
NumWebVisitsMonth             int64
ID                           object
dtype: object

In [11]:
df_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Income             43170 non-null  int64
 1   Kidhome            43170 non-null  int64
 2   Teenhome           43170 non-null  int64
 3   Dt_Customer        43170 non-null  datetime64[ns]
 4   NumWebVisitsMonth  43170 non-null  int64
 5   ID                 43170 non-null  object
dtypes: datetime64[ns](1), int64(4), object(1)
memory usage: 2.0+ MB

In [12]:
df_clientes.describe()

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth
count,43170.000000,43170.000000,43170.000000,43170,43170.000000
mean,93227.389622,1.004749,0.998633,2013-05-11 22:09:47.407922176,16.591290
min,5841.000000,0.000000,0.000000,2012-01-01 00:00:00,1.000000
25%,49608.000000,0.000000,0.000000,2012-07-16 00:00:00,9.000000
50%,93009.500000,1.000000,1.000000,2013-03-01 00:00:00,17.000000
75%,136740.500000,2.000000,2.000000,2014-03-28 00:00:00,25.000000
max,180802.000000,2.000000,2.000000,2014-12-31 00:00:00,32.000000
std,50498.181989,0.815996,0.816008,NaN,9.241769

## Continuar